### ISSUE TITLE
PowerBI Report Server (September 2019) Custom Authentication 401 Unauthorized 

### ISSUE THREAD

**Issue by metinsevindik** [jonbgallant/PowerBI-visuals-liquidFillGauge#10]
Hi,

I have a problem in a powerbi report include this visual.
[Error details](https://github.com/microsoft/PowerBI-visuals/issues/578)

**Comment by SatyaKSN** [comment]
I am also getting the same issue.. is there any solution for this

**Comment by metinsevindik** [comment]
I removed last some windows server updates. For now resolved

**Comment by SatyaKSN** [comment]
> I removed last some windows server updates. For now resolved

Which windows version is yours? and could you let me know the patch numbers if you have please

**Comment by jongio** [comment]
Are you only seeing with this visual or all custom visuals?

**Comment by SatyaKSN** [comment]
Thankq for your quick response.  I am only using this text filter visual.. it's working fine with IE edge but not in Chrome and Mozilla.
My report server is hosted on windows server 2016 and using the October release of power bi report server.

**Comment by jongio** [comment]
I, unfortunately, have no experience with PBI report server.  I don't think this is a bug with my visual, but all custom visuals, so let's track the issue here: https://github.com/microsoft/PowerBI-visuals/issues/578

**Comment by SatyaKSN** [comment]
> I, unfortunately, have no experience with PBI report server. I don't think this is a bug with my visual, but all custom visuals, so let's track the issue here: [microsoft/PowerBI-visuals#578](https://github.com/microsoft/PowerBI-visuals/issues/578)

Okay thanks

**Comment by jongio** [comment]
All the links in this issue are dead. Please comment if you still see this issue.
