### ISSUE TITLE
Liquid fill does not fill to right decimal 

### ISSUE THREAD

**Issue by malcolmwun** [jonbgallant/PowerBI-visuals-liquidFillGauge#3]
![liquid1](https://cloud.githubusercontent.com/assets/26153644/23534123/d5d8fca8-0009-11e7-8dc9-2a81a3894368.JPG)
![liquid2](https://cloud.githubusercontent.com/assets/26153644/23534124/d8ce8a54-0009-11e7-9e09-404a1e00e696.JPG)

Hi Jon, I LOVE this visual! BUt I cannot get my head around refresh issue. Refer the 2 image I attach. As you can see I have set the convert 1.22 to 122% format..  However when I select from a filter the Visual returns 1.22% . Ideally it should remain 122% .. Please help as I have convince our organisation this is the best Performance visual

**Comment by jongio** [comment]
Sorry for delay.  Please try this new version.  It now has a calculate percentage option, which just shows the percentage based on current value and max value.

There's also a new field called "Multiply By" which allows you to correct for decimal places.

Let me know if you have issues.

https://github.com/jonbgallant/PowerBI-visuals-liquidFillGauge/raw/master/liquidFillGauge/dist/liquidFillGauge.pbiviz

**Comment by malcolmwun** [comment]
Thanks for the the new version- but it did not work.. Please refer the BEFORE and AFTER images when I apply a country filter at Top left (yellow).. 
![before](https://cloud.githubusercontent.com/assets/26153644/26381321/4944a30c-4067-11e7-83e8-b4ecbdd0e718.JPG)
![after](https://cloud.githubusercontent.com/assets/26153644/26381325/4ef9b5c6-4067-11e7-8710-dc38f8bdaf8a.JPG)

**Comment by malcolmwun** [comment]
Thanks for the the new version- but it did not work.. Please refer the BEFORE and AFTER images when I apply a country filter at Top left (yellow)
![before](https://cloud.githubusercontent.com/assets/26153644/26381390/c8661d3c-4067-11e7-970f-ab1d49276da3.JPG)
![after](https://cloud.githubusercontent.com/assets/26153644/26381394/cd5d74e8-4067-11e7-9572-1b19ab0e0ba0.JPG)

**Comment by jongio** [comment]
Pls try this version https://www.dropbox.com/s/oal9whzwjdvn972/liquidFillGauge-sewell.pbiviz?dl=0


________________________________

**Comment by malcolmwun** [comment]
it worked!!!! I AM Very happy. Will you have this version updated in PBI Custom visual site?

**Comment by jongio** [comment]
Issue is fixed with latest push: https://github.com/jonbgallant/PowerBI-visuals-liquidFillGauge/raw/master/liquidFillGauge/dist/liquidFillGauge.pbiviz

I've also submitted it to the public library.
