### ISSUE TITLE
Correctly interpreting %

### ISSUE THREAD

**Issue by mscottsewell** [jonbgallant/PowerBI-visuals-liquidFillGauge#4]
(BTW - cool visual - thanks for sharing it!)

I have a measure that is already a percentage but it looks 'odd' when I display it in the visual - ( I had to create a second copy of the value and multiply it by 100 in order to get it to 'look' right.

Could you add support for just passing in a ratio and displaying that value directly (rather then re-interpreting it as a ratio of a ratio?)

Thanks much!

**Comment by mscottsewell** [comment]
Here's what my value looks like - 32% gets displayed as 0.32%
![liquid](https://cloud.githubusercontent.com/assets/6276300/25974389/796285de-366e-11e7-80f2-6f73ab14916a.gif)

**Comment by jongio** [comment]
Sorry for delay.  Please try this new version.  It now has a calculate percentage option, which just shows the percentage based on current value and max value.

There's also a new field called "Multiply By" which allows you to correct for decimal places.

Let me know if you have issues.

https://github.com/jonbgallant/PowerBI-visuals-liquidFillGauge/raw/master/liquidFillGauge/dist/liquidFillGauge.pbiviz

**Comment by mscottsewell** [comment]
Hi Jon - I am not seeing your 'Multiply By' option - did the updated code get committed?

Also - is there a chance of making the Max/Min values parameters - so I can optionally pass the max/min/actual values and have the visual display the percentage of max?  (I can and am already doing this already in DAX, but just an idea.)

**Comment by jongio** [comment]
It's here
![image](https://cloud.githubusercontent.com/assets/2163001/26378752/cfb4f1be-3fca-11e7-8f15-966b14a21e3e.png)


Thx for suggestion.  Can you add as another issue so I can track it?

**Comment by mscottsewell** [comment]
That option is not in the version I downloaded this afternoon…

**Comment by jongio** [comment]
It might be cached.  Try creating a new report with the new visual

**Comment by mscottsewell** [comment]
No luck -

**Comment by mscottsewell** [comment]
Oh snap
It was cached.
I had to delete and re-add it.
Thanks!

**Comment by mscottsewell** [comment]
It’s really spotty on maintaining the “Multiply by 100” setting – as I change background colors etc / or change other options – the value recalculates without the X100 option – but flipping it again gets the value back. – something strange is amuck.

What’s the best info I can collect for you to help troubleshoot?

From: Scott Sewell
Sent: Tuesday, May 23, 2017 6:36 PM
To: 'jonbgallant/PowerBI-visuals-liquidFillGauge' <reply@reply.github.com>; jonbgallant/PowerBI-visuals-liquidFillGauge <PowerBI-visuals-liquidFillGauge@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [jonbgallant/PowerBI-visuals-liquidFillGauge] Correctly interpreting % (#4)

Oh snap
It was cached.
I had to delete and re-add it.
Thanks!

**Comment by jongio** [comment]
Issue is fixed with latest push: https://github.com/jonbgallant/PowerBI-visuals-liquidFillGauge/raw/master/liquidFillGauge/dist/liquidFillGauge.pbiviz

I've also submitted it to the public library.
