### ISSUE TITLE
Problem resetting value to 0

### ISSUE THREAD

**Issue by laiariu** [jonbgallant/PowerBI-visuals-liquidFillGauge#6]
Hi, 
Thanks for the visual, it is great! However I found a problem when I am using the Liquid Fill Gauge and the Power BI slicer to select years. I am using the Gauge with percentages and it works properly when I select a year with data. The problem comes when I select a year with no data and the visual goes to 0%. After that, if I select the year with dat, the visual gets stucked at 0% and doesn't filll. I attach some images here for further information: 

First I select 2016 as a year with data:
![image](https://user-images.githubusercontent.com/34026607/33262618-257a620c-d367-11e7-8c5c-4fe635207af7.png)
Then I select 2017 that has no data and the visual goes to 0%
![image](https://user-images.githubusercontent.com/34026607/33262640-39e42a16-d367-11e7-86ae-c7c5d8d69391.png)
Afterwards, I select 2016 again but the visual doesn't fill.
![image](https://user-images.githubusercontent.com/34026607/33262651-45630984-d367-11e7-965a-15a1d608d78e.png)

I don't know if it is a visual problem or that I am not configuring it properly. Could you help me? I am using the latest release from 27th June.

Thanks in advance.

**Comment by jongio** [comment]
Thanks for letting me know.  I should be able to have a look at this in the next couple of days.

**Comment by jongio** [comment]
Sorry for delay on this...I realize it has been a year.  I completely forgot about this.

I just tested with the latest version and with this pbix attached and I cannot repro.  

Can you please try to repro and let me know if you still have the issue?

[YearDataReset.zip](https://github.com/jongio/PowerBI-visuals-liquidFillGauge/files/2661864/YearDataReset.zip)

**Comment by jongio** [comment]
Closing for now. LMK if you can repro.
