### ISSUE TITLE
Enhancement Idea - Max Value to be dynamic based on measure.

### ISSUE THREAD

**Issue by Raynok** [jonbgallant/PowerBI-visuals-liquidFillGauge#7]
![image](https://user-images.githubusercontent.com/15869822/33817854-708fe030-de4a-11e7-8f42-e5891f4e5c8f.png)

![image](https://user-images.githubusercontent.com/15869822/33817866-8331cb18-de4a-11e7-84ea-51deb80398f6.png)

For instance, each month x amount of units are built by lets say 10 individuals, with a target of xx per month. The page consists the entire year's data with a month and individual user slicer for filtering into the data, It would be great to have the ability to have the visual adjust its max value using measures. 

When a month is selected,
The visual should show the total units for the month with a target for the month.

When no month is selected,
The visual should show total units for the year with a target for the year. 

Hope my explanation make sense.

Best Regards
& thank you for the awesome visual

**Comment by jongio** [comment]
@Raynok - Apologies, but binding a measure to a format property is not supported.  I'll gladly update once the PBI team adds that capability, but for now we are blocked on that.  I'll do my best to track that feature.
