### ISSUE TITLE
Option to remove/adjust the decimal numbers

### ISSUE THREAD

**Issue by Ragha2207** [jonbgallant/PowerBI-visuals-liquidFillGauge#8]

**Comment by jongio** [comment]
@Ragha2207 

Here's what I think you mean.

I want to :
1. round up
2. round down
3. remove

decimal values.


Does that cover what you are asking?

**Comment by jongio** [comment]
@Ragha2207 - I added support to apply a Math function to the Text value.  You can find it in Format->Text->Function.  Let me know if this meets your needs and if you see any issues with it.

https://github.com/jongio/PowerBI-visuals-liquidFillGauge/raw/master/liquidFillGauge/dist/liquidFillGauge.pbiviz


![image](https://user-images.githubusercontent.com/2163001/43110894-499cbc82-8ea3-11e8-9b51-906fdd3faa22.png)

![image](https://user-images.githubusercontent.com/2163001/43110903-52e7c886-8ea3-11e8-997f-ba5705c28f6d.png)

**Comment by Ragha2207** [comment]
Yes, Perfect. Thank you.
